export const mangoDrink = {
  drinks: [
    {
      idDrink: '12716',
      strDrink: 'Mango Orange Smoothie',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Other / Unknown',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Highball Glass',
      strInstructions: 'Throw everything into a blender and liquify.',
      strInstructionsES: null,
      strInstructionsDE: 'Alles in einen Mixer geben und aufschlagen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Getta tutto in un frullatore e liquida.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vdp2do1487603520.jpg',
      strIngredient1: 'Mango',
      strIngredient2: 'Orange',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 ',
      strMeasure2: '2 ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-02-20 15:12:01',
    },
  ],
};

export const turkeyMeal = {
  meals: [
    {
      idMeal: '52845',
      strMeal: 'Turkey Meatloaf',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'British',
      strInstructions: 'Heat oven to 180C/160C fan/gas 4. Heat the oil in a large fryin.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ypuxtw1511297463.jpg',
      strTags: 'Alcoholic',
      strYoutube: 'https://www.youtube.com/watch?v=mTvlmY4vCug',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Garlic',
      strIngredient4: 'Worcestershire Sauce',
      strIngredient5: 'Tomato Puree',
      strIngredient6: 'Turkey Mince',
      strIngredient7: 'Eggs',
      strIngredient8: 'Breadcrumbs',
      strIngredient9: 'Barbeque Sauce',
      strIngredient10: 'Cannellini Beans',
      strIngredient11: 'Parsley',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 tblsp ',
      strMeasure2: '1 large',
      strMeasure3: '1 clove peeled crushed',
      strMeasure4: '2 tblsp ',
      strMeasure5: '3 tsp',
      strMeasure6: '500g',
      strMeasure7: '1 large',
      strMeasure8: '85g',
      strMeasure9: '2 tblsp ',
      strMeasure10: '800g',
      strMeasure11: '2 tblsp ',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/turkey-meatloaf',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
